#file: noinspection SpellCheckingInspection
name: ACTest
version: 1.0
main: kawaii.nahida.actest.ACTestPlugin
api-version: 1.8
author: NekoCurit
description: 猫猫的测试服务器基础插件
commands:
  clear:
    description: 清空自身背包
    usage: /clear
  ec:
    description: 打开自身末影箱容器
    usage: /ec
  fly:
    description: 开启或关闭飞行模式
    usage: /fly
  food:
    description: 设置自身饥饿值
    usage: /food <饥饿值>
  give:
    description: 给予自身物品
    usage: /give <物品名称> [数量]
  health:
    description: 设置自身生命值
    usage: /health <生命值>
  item:
    description: 快速获取物品
    usage: /item
  kill:
    description: 杀死自身
    usage: /kill
  spawn:
    description: 返回出生点
    usage: /spawn
